Feature branch
addod19/Enumerable_Methods pull request #1
Opened 2019-09-09 18:25 UTC by addod19

2019-09-09 22:46 UTC, maelfosso requested changes
Hello @addod19 ,

# GReat work !! :smile:  You deserved a standing ovation :clap: 

There is just one bug to fix in the `inject` function. Take a lot at the comment below please.

Kindly fix it a submit a new code review request.
Thanks

2019-09-09 22:46 UTC, maelfosso commented on enum.rb
> +  end
Sorry :disappointed: there is a bug
```ruby
irb(main):043:0> [5,6,7,8,9,10].inject(5) { |sum, n| sum + n } 
=> 50
irb(main):044:0> [5,6,7,8,9,10].my_inject(5) { |sum, n| sum + n } 
=> 45
irb(main):045:0> [5,6,7,8,9,10].inject(5) { |prod, n| prod * n } 
=> 756000
irb(main):046:0> [5,6,7,8,9,10].my_inject(5) { |prod, n| prod * n } 
=> 151200
```

2019-09-10 00:25 UTC, bellom reviewed
...

2019-09-10 00:25 UTC, bellom commented on enum.rb
> +  def my_inject(*args)
## Opps, we still need to work on `inject`, got the below error;
![image](https://user-images.githubusercontent.com/31897434/64574938-4ee26f00-d369-11e9-89c4-f7380d3d4990.png)
Note; you can always user `my_each` method in the file  to make your work easier.

2019-09-10 00:28 UTC, bellom requested changes
Hi @addod19,
**NOTE: Always read the pathwright instructions before starting the project to avoid the need of sending another code review, according to the pathwright you are to use Git Flow not GitHub Flow.**
_Short Explanation Hint:
GitHub Flow: Pull Requests is raise from feature branches to the master.
Git Flow: Pull Requests is raise from feature branches to the development._

**Make sure to use Git flow in the next project and also add Linter's check on your PR page.**

_Just one thing to do, checkout my comment._

**Kindly re-submit for review after the `my_inject` method :slightly_smiling_face: Thumps -up await you....**

2019-09-10 01:42 UTC, bellom requested changes
Hi @addod19, 
## Wonderful work using `Git flow` and Good job correcting all the issues from previous reviews.
**Just one thing to do which is `_Required_`;**
1.  Fix all errors on linter, checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
![image](https://user-images.githubusercontent.com/31897434/63073279-0e393680-bf20-11e9-9c84-f142caf1e675.png)

**_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_**

2019-09-10 14:59 UTC, bolah2009 approved these changes
## It's a :+1: from me @addod19  :smile: 

Nice Job implementing all requested changes

#### I strongly recommend updating this PR description.
   ![update-PR-description](https://user-images.githubusercontent.com/36057474/64303100-8672a500-cf7e-11e9-999c-d23c06358f0e.gif)

## Go ahead and merge to master :rocket: 

#### Also, don't forget to submit project completion form. :blush: 

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-10 15:10 UTC, addod19 commented
# Custom Enumerable Methods
This project is setup with .rubocop.yml and .stickler.yml file. The code is reviewed

2019-09-10 15:11 UTC, merged